spring.application.name=SYSNotification
# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/notificaciones_db
spring.datasource.username=postgres
spring.datasource.password=salsaypicante2$

# Hibernate creará/actualizará las tablas automáticamente basado en tus clases
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# CONFIGURACIÓN DE CORREO (Ejemplo Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santif.arevalo@gmail.com
spring.mail.password=zplk iyns xqxx fpmw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true